---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
- name: 'ğŸ—ƒï¸ Everything Else'
  url: https://github.com/getpelican/pelican/discussions
  about: |
    Do you have a question/issue that does not fall into any of the other categories?
- name: 'ğŸ’¬ Pelican IRC Channel'
  url: https://web.libera.chat/?#pelican
  about: |
    Chat with the community, ask questions, and learn about best practices.
